name: offline_docs_server
description: App offline docs server bloc
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.5
  app_database: any
  app_logging: any
  docs_server: any
  drift: ^2.26.1
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^6.0.0