name: offline_docs_server
description: App offline docs server bloc
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.5
  app_database: any
  app_logging: any
  drift: ^2.26.1
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  network_info_plus: ^6.1.2
  path_provider: ^2.1.5
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.20.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  lints: ^6.0.0