name: app_provider
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  bloc: ^9.0.0
  dio: ^5.7.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17

  theme_bloc: any
  hex_api: any
  hex_auth_bloc: any
  hex_search_bloc: any
  favorite_package_bloc: any
  hex_doc_bloc: any
  offline_docs_server: any
  app_database: any
  app_secure_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
