name: docs_server
description: HTTP server for serving offline Hex documentation
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  network_info_plus: ^6.1.2
  path: ^1.8.0
  app_logging: any

dev_dependencies:
  test: ^1.20.1
  lints: ^6.0.0
