name: hex_doc_bloc
description: App hex_doc bloc
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  equatable: ^2.0.5
  path: ^1.9.0 # Use the latest version
  http: ^1.2.1
  archive: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.20.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  lints: ^6.0.0
